In [2]:
import math
import pandas as pd
import numpy as np
from datetime import datetime
from tqdm.notebook import tqdm
tqdm.pandas()

In [3]:
customers_df = pd.read_csv("../data/olist_customers_dataset.csv")
geoloc_df = pd.read_csv("../data/olist_geolocation_dataset.csv")
order_items_df = pd.read_csv("../data/olist_order_items_dataset.csv")
order_payments_df = pd.read_csv("../data/olist_order_payments_dataset.csv")
order_reviews_df = pd.read_csv("../data/olist_order_reviews_dataset.csv")
order_df = pd.read_csv("../data/olist_orders_dataset.csv")
products_df = pd.read_csv("../data/olist_products_dataset.csv")
sellers_df = pd.read_csv("../data/olist_sellers_dataset.csv")
product_category_name_translation_df = pd.read_csv("../data/product_category_name_translation.csv")

In [17]:
orders_products_reviews_df = order_df.merge(
    order_reviews_df.merge(
            order_items_df.merge(products_df,
                                 on="product_id", 
                                 how='left'),
            on="order_id",
            how="left"),
    on="order_id",
    how="left"
)

In [18]:
orders_products_reviews_df.reset_index(drop=True, inplace=True)

In [6]:
orders_products_reviews_df.to_csv('../data/orders_products_reviews_dataset.csv', index=False)

In [19]:
# orders_products_reviews_df.isna().sum()
orders_products_reviews_df = orders_products_reviews_df.select_dtypes(include=[np.number])

In [14]:
# orders_products_reviews_df

orders_products_reviews_df["product_weight_g"] = orders_products_reviews_df["product_weight_g"].fillna(orders_products_reviews_df["product_weight_g"].median())
orders_products_reviews_df["product_length_cm"] = orders_products_reviews_df["product_length_cm"].fillna(orders_products_reviews_df["product_length_cm"].median())
orders_products_reviews_df["product_height_cm"] = orders_products_reviews_df["product_height_cm"].fillna(orders_products_reviews_df["product_height_cm"].median())
orders_products_reviews_df["product_width_cm"] = orders_products_reviews_df["product_width_cm"].fillna(orders_products_reviews_df["product_width_cm"].median())
# orders_products_reviews_df["review_comment_message"].fillna("No review", inplace=True)

In [20]:
orders_products_reviews_df.isna().sum()

review_score                   768
order_item_id                 1527
price                         1527
freight_value                 1527
product_name_lenght           3125
product_description_lenght    3125
product_photos_qty            3125
product_weight_g              1545
product_length_cm             1545
product_height_cm             1545
product_width_cm              1545
dtype: int64

,index,review_score,order_item_id,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,0,4.0,1.0,29.99,8.72,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,1,4.0,1.0,118.70,22.76,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,2,5.0,1.0,159.90,19.22,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,3,5.0,1.0,45.00,27.20,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,4,5.0,1.0,19.90,8.72,38.0,316.0,4.0,250.0,51.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...
110768,113894,4.0,1.0,174.90,20.10,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
110769,113895,5.0,1.0,205.99,65.02,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
110770,113896,2.0,1.0,179.99,40.59,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
110771,113897,2.0,2.0,179.99,40.59,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
110772,113898,5.0,1.0,68.50,18.36,45.0,569.0,1.0,150.0,16.0,7.0,15.0